### ISSUE TITLE
closing brace missing

### ISSUE THREAD

**Issue by Orchad** [bayko/365-Secure-Score-Powershell#2]
https://github.com/bayko/365-Secure-Score-Powershell/blob/eeaf4e0d35e476982ddf22bee82952e4ec23f8b6/SecureScore.ps1#L274-L279

Hello,

First thanks for your job ! 

I saw there is a little bug in your script there is a missing closing brace at line 279.

Best regards

Lionel

**Comment by bayko** [comment]
Thanks for pointing this out Lionel. I didn't realize people were actually using the script! (or at least parts of it). I just turned all the steps into isolate modules now to make it more re-usable. Might consider adding some more to this repo down the road if its of value to people - since in the last year secure score has added alot more metrics!
